server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost/bli
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format-sql: true
    hibernate:
      #create, create-drop, update, none
      ddl-auto: update

    show-sql: true